[workspace.package]
version = "0.3.5"
repository = "https://github.com/DuckLogic/intid.rs"
authors = ["Techcable <git@techcable.net>"]
license = "MIT OR Apache-2.0"
# 1.56 - 2021 edition
# 1.61 - Vec::retain_mut
# 1.64 - workspace.package
# 1.65 - GAT
# 1.68 - sparse index
# 1.71 - syn@3
#
# if changed, keep in sync with CI
rust-version = "1.71"
edition = "2021"

[workspace]
resolver = "2"
members = ["intid", "intid-core", "idmap", "intid-allocator", "intid-derive"]

[workspace.dependencies]
# crate dependencies
intid-derive = { path  = "intid-derive", version = "0.3.2" }
intid-core = { path = "intid-core", version = "0.3.2"}
intid = { path  = "intid", version = "0.3.2" }
idmap = { path  = "idmap", version = "0.3.2" }

[workspace.lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
# NOTE: Cannot restict this to derive crate,
# because you cannot selectively override `lints.workspace = true`
check-cfg = ['cfg(intid_derive_use_expander)']

[workspace.lints.clippy]
## groups ##
cargo = { priority = -1, level = "warn" }
pedantic = { level = "warn", priority = -1 }

# restrictions
alloc_instead_of_core = "deny"
std_instead_of_alloc = "deny"
std_instead_of_core = "deny"
redundant_test_prefix = "warn" # name test_foo is redundant with #[test] attr

# safety
undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "deny"

## aggressively lint casts ##
# in an ideal world, overflowing casts would panic
# linting them (with deny) is the second best option
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_sign_loss = "deny"
char_lit_as_u8 = "deny"
cast_ptr_alignment = "deny"
fn_to_numeric_cast = "deny"
fn_to_numeric_cast_any = "deny"
fn_to_numeric_cast_with_truncation = "deny"
cast_lossless = "allow" # lossless casts are fine, lints will catch if types change
ptr_as_ptr = "allow" # pointer casts are fine as long as they don't violate another rule

#
# excessively pedantic (even for clippy::pedantic)
#
too_many_lines = "allow"
# We don't put #[must_use] on len
must_use_candidate = "allow"
return_self_not_must_use = "allow"
items_after_statements = "allow"
# these can actually make things clearer
redundant_else = "allow"
needless_continue = "allow"
if_not_else = "allow"
# done intentionally to make sure certian code type checks
no_effect_underscore_binding = "allow"
# too many false positives
missing_panics_doc = "allow"

[workspace.metadata.cargo-reedme]
note = "Do not edit - automatically generated by cargo-reedme"
